### ISSUE TITLE
Get Media Keys working

### ISSUE THREAD

**Issue by mountainash** [mountainash/Mixcloud-Play#26]
I've never experienced them working even in the original App. 

Looks like it should be possible https://www.electronjs.org/docs/api/global-shortcut

**Comment by mountainash** [comment]
The most important "Play/Pause" is working again.

## ToDo:

- [ ] Make "Next" skip forward
- [ ] Make "Back" skip backwards
- [ ] It would be nice to add a modal to tell the user about needing to enable macOS: System Preferences > Security & Privacy > Accessibility > Mixcloud Play to enable use of the media keys
- [ ] use the "audio" element methods instead of the current DOM/CSS (could break due to className changes) eg. https://googlechrome.github.io/samples/media-session/audio.html

**Comment by mountainash** [comment]
Using the "aria" attribute in the DOM to link to the "seek" buttons - seems more stable than the React.js generated class names.

**Comment by mountainash** [comment]
Found this which might come in handy for this issue: https://github.com/salomvary/soundcleod/commit/b9b37e2bfbe9c8f5dab07c4c050c47a6da08cbc5

**Comment by oisinq** [comment]
Hey, is this issue fixed? Play/Pause doesn't seem to work for me on the latest release (I don't have Pro).

Also I'm happy to help on this project, you've done a lot of great work so far. I'm new to Electron, but I've used Mixcloud and this app a bit. I've got some free time and wouldn't mind trying some OSS work.

**Comment by mountainash** [comment]
Have you allowed the App Accessibility access from the Apple System Preferences and then restarted the App?

Play/Pause (and even fast forward) aren’t Pro or Select dependent - they should work on the free Mixcloud plan.

There’s plenty to do and many more ideas to be had; feel free to fork and hack away at it 🤓

**Comment by oisinq** [comment]
Restarting the app worked for me. Mixcloud Play was already on that list and selected for me, which is a bit weird. Works now anyway, thanks!

**Comment by mountainash** [comment]
References:
- https://github.com/salomvary/soundcleod/issues/119
- https://github.com/salomvary/soundcleod/issues/78

**Comment by mountainash** [comment]
This has been working for a few years now.
